plugins { id 'com.android.application' }
android {
    namespace 'com.apno.party'
    compileSdk 34
    defaultConfig {
        applicationId 'com.apno.party'
        minSdk 23
        targetSdk 34
        versionCode 2
        versionName '0.2'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
